name: Define pytest

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  pytest:
    runs-on:
      - ${{ matrix.os }}
      - self-hosted
    strategy:
      matrix:
        os: [Linux]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install --upgrade -r requirements.txt; fi
    - name: Run tests with pytest
      run: |
        pytest src --skip-linting
